---
- name: destroy the workshop resources
  hosts: workstation
  gather_facts: no
  become: no
  vars_files: ../group_vars/all
  vars:
    destroy_workshop: no
  tasks:
  - name: destroy workshop
    include_role:
      name: ../roles/destroy-workshop
    when: destroy_workshop|bool == true

# destroys the workstation created by launch-workshop-workstation.yml
# deletes the keys, subnets, etc
- name: destroy workstation resources
  hosts: localhost
  gather_facts: no
  vars_files: ../group_vars/all
  vars:
    destroy_workstation: no
    aws_vpc_name: "{{ workshop.name }} vpc"
    aws_vpc_cidr: "11.22.33.0/24"
    aws_subnet_name: "{{ workshop.name }} subnet"
    aws_igw_name: "{{ workshop.name }} igw"
    aws_route_name: "{{ workshop.name }} route"
    ec2_key_directory: keys
    aws_role: deploy-workshop-workstation
    aws_ostype: rhel8
    aws_vmname: "{{ workshop.name }}-workstation"
    aws_assign_public_ip: yes
    aws_volume_size: 150
    aws_security_group_name: "{{ workshop.name }}-sg-ansible"
    aws_security_group_allow_cidr: "0.0.0.0/0"
    rhel6_ami_id: ami-1643ff7e
    centos7_ami_id: ami-0affd4508a5d2481b
    rhel7_ami_id: ami-0315fe0b0bfdfedda
    rhel8_ami_id: ami-058f90e71a7d69115
    aws_instance_type: t3.medium
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws.keyid }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws.secret }}"
  tasks:
  - name: destroy workstation
    include_role:
      name: ../roles/destroy-workstation
    when: destroy_workstation|bool == true
