---
- name: stop all resources in the workshop vpc
  hosts: localhost
  gather_facts: no
  vars_files: ../group_vars/all
  vars:
    aws_workstation_vpc: "{{ workshop.name }} vpc"
    aws_workshop_vpc: "{{ workshop.name }}-vpc"
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws.keyid }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws.secret }}"
  tasks:
    - name: "get the vpc ids"
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ item }}"
      register: vpc
      loop:
      - "{{ aws_workshop_vpc }}"
      - "{{ aws_workstation_vpc }}"

    - name: dump var
      debug: var=vpc

    - name: Gather information about any instances running in the workshop vpc
      community.aws.ec2_instance_info:
        region: "{{ aws.region }}"
        filters:
          vpc-id: "{{ item.vpc_id }}"
          instance-state-name: [ "running"]
      register: wrkshop_instances1
      when:
      - vpc.results[0].vpcs|length > 0
      loop: "{{ vpc.results[0].vpcs }}"

    - name: Gather information about any instances running in the workstation vpc
      community.aws.ec2_instance_info:
        region: "{{ aws.region }}"
        filters:
          vpc-id: "{{ item.vpc_id }}"
          instance-state-name: [ "running"]
      register: wrkshop_instances2
      when:
      - vpc.results[1].vpcs|length > 0
      loop: "{{ vpc.results[1].vpcs }}"

    - name: dump var
      debug: var=wrkshop_instances1

    - name: dump var
      debug: var=wrkshop_instances2

    - name: "stop all running ec2 instance(s) in the {{ aws_workshop_vpc }} workshop vpc"
      amazon.aws.ec2:
        region: "{{ aws.region }}"
        instance_ids: 
          - "{{ item.instance_id }}"
        state: stopped
      loop: "{{ wrkshop_instances1.results[0].instances }}"
      when:
      - vpc.results[0].vpcs|length > 0
      - wrkshop_instances1.results[0].instances|length > 0

    - name: "stop all running ec2 instance(s) in the {{ aws_workstation_vpc }} workstation vpc"
      amazon.aws.ec2:
        region: "{{ aws.region }}"
        instance_ids: 
          - "{{ item.instance_id }}"
        state: stopped
      loop: "{{ wrkshop_instances2.results[0].instances }}"
      when:
      - vpc.results[1].vpcs|length > 0
      - wrkshop_instances2.results[0].instances|length > 0

